services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database
  mongo:
    image: mongo:7
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Main Backend API
  backend:
    build: ./Dietbackend
    container_name: diet-backend
    env_file: .env
    depends_on:
      - rabbitmq
      - mongo
      - redis
    ports: 
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://admin:password@mongo:27017
      - REDIS_URL=redis://redis:6379

  # AI Service
  ai_service:
    build: ./dietaiservices
    container_name: diet-ai
    env_file: .env
    depends_on:
      - rabbitmq
      - mongo
      - redis
    ports: 
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
      - ./google-credentials.json:/app/google-credentials.json:ro
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://admin:password@mongo:27017
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json

  # AI Worker (separate worker processes)
  ai_worker:
    build: ./dietaiservices
    env_file: .env
    depends_on:
      - rabbitmq
      - mongo
      - redis
      - ai_service
    volumes:
      - ./logs:/app/logs
      - ./google-credentials.json:/app/google-credentials.json:ro
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://admin:password@mongo:27017
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    command: ["python", "worker.py"]
    deploy:
      replicas: 2

  # Frontend
  frontend:
    build: ./Dietagentfrontend
    container_name: diet-frontend
    env_file: .env
    depends_on:
      - backend
      - ai_service
    ports: 
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_AI_API_URL=http://ai_service:8001
      
  # Mental Health AI Service
  mental_health_service:
    build: ./mentalhealthaiservices
    container_name: mental-health-ai
    ports: 
      - "8002:8001"
    volumes:
      - ./logs:/app/logs
    environment:
      - PORT=8001
      
  # Mental Health Frontend
  mental_health_frontend:
    build: ./Mentalhealthfrontend
    container_name: mental-health-frontend
    depends_on:
      - mental_health_service
    ports: 
      - "5175:5175"
    environment:
      - PORT=5175

volumes:
  mongo_data:
  rabbitmq_data:
  redis_data:

networks:
  default:
    driver: bridge
