version: '3.8'

services:
  mentalhealthservice:
    build: 
      context: ./mentalhealthaiservices
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - PORT=8001
    networks:
      - mentalhealth-network

  mentalhealthfrontend:
    build:
      context: ./Mentalhealthfrontend
    ports:
      - "5175:80"
    depends_on:
      - mentalhealthservice
    networks:
      - mentalhealth-network

networks:
  mentalhealth-network:
    driver: bridge
